sudo: required

language: scala

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x

script:
  - sbt "aocJVM/testOnly aoc.Day*Spec -- -n aoc.BuildTest"
  - sbt aocJVM/run
  #- sbt aocNative/run


