sudo: required

language: scala

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

before_install:
  - bash bin/travis_setup.sh

script:
  - sbt "aocJVM/testOnly aoc.Day*Spec -- -n aoc.SolutionTest"
  - sbt aocJVM/run
  - sbt aocNative/run


